### ISSUE TITLE
Player window not working

### ISSUE THREAD

**Issue by TheKerth** [JakobKallin/RPG-Ambience#74]
When I try to open the player in a separate window it just load a black window without contents; tried with Chrome and Firefox. The page's code is here: http://pastebin.com/D5R78a8X

[edit, nevermind, I didn't realize that the window was supposed to be empty until a hotkey was pressed. I'm absolutely dumb but instructions could be clearer]

**Comment by JakobKallin** [comment]
Thanks for the report; I have in fact seen other users get tripped up by this. The player window will be remade for the next version and the [RPG Ambience Soundboard alpha](http://blog.rpg-ambience.com/articles/soundboard-alpha), and I'll keep your feedback in mind for that.
